{
    "name": "AssetFlow",
    "version": "1.0",
    "summary": "Asset management and forecasting",
    "author": "Your Company",
    "depends": ["base", "stock", "account_asset", "maintenance", "hr"],
    "data": [
        "security/assetflow_security.xml",
        "security/ir.model.access.csv",
        "views/asset_views.xml",
        "views/maintenance_views.xml",
        "views/stock_views.xml",
        "views/forecast_views.xml",
        "views/prediction_views.xml",
        "views/audit_views.xml",
        "views/transfer_views.xml",
        "views/dashboard.xml",
        "views/menu.xml",
        "reports/asset_report.xml",
        "reports/maintenance_report.xml",
        "reports/audit_report.xml",
        "data/demo_data.xml",
        "data/cron_jobs.xml",
        "data/automation_actions.xml",
    ],
    "installable": True,
}
